{% set name = "nc-time-axis" %}
{% set version = "1.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72d80f492f34bbf59490838d8cb3d92f14e88900b0ee35498b2b33c82795eb81

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - cftime >=1.5
    - matplotlib-base
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - nc_time_axis

about:
  home: https://github.com/SciTools/nc-time-axis
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Provides support for a cftime axis in matplotlib

extra:
  recipe-maintainers:
    - lbdreyer
    - ocefpaf
    - pelson
    - bjlittle
    - spencerkclark
